### ISSUE TITLE
About label entropy

### ISSUE THREAD

**Issue by mugpeng** [LungCellAtlas/HLCA_reproducibility#11]
the paper, mentioned:
> For example, the immune cluster with the highest label entropy contained many cells that were originally mislabeled as monocytes and macrophages but were actually type 2 dendritic cells (Fig. 3c and Extended Data Fig. 1b). Thus, populations with high label entropy identify mislabeled cell types, indicating the need for consensus re-annotation of the integrated atlas

However, it seems to have less entropy when 2 cell types are actually one. Why the label entropy is reversely highest? And do you explore the reasons why populations with high label entropy identify mislabeled cell types? Are there any biological discoveries?

Thank you.
Peng

**Comment by LisaSikkema** [comment]
Hi @mugpeng ,

Could you maybe explain a bit more with what you mean with "when 2 cell types are actually one"?
Also not sure if I understand your question "Why the label entropy is reversely highest?" 

> do you explore the reasons why populations with high label entropy identify mislabeled cell types

Label entropy was calculated on clusters, and high label entropy by definition means cells within these clusters were labeled in contradictory ways. This can either be because the cluster simply includes two cell types, or because only of the two (or more) labelings was correct. Aanalysis of marker expression can clarify which of the two is going on, as also shown in the example in the paper. Not sure if that answers your question..

**Comment by mugpeng** [comment]
For "when 2 cell types are actually one", which is my personal understanding from the paper:
> For example, the immune cluster with the highest label entropy contained many cells that were originally mislabeled as monocytes and macrophages but were actually type 2 dendritic cells (Fig. 3c and Extended Data Fig. 1b).
If the cluster of cells DC-2 is incorrectly labeled as mono and macro, then the entropy should be low (only one cell type).

Besides, could you please explain "This can either be because the cluster simply includes two cell types, or because only of the two (or more) labelings was correct" with more specific details, I just can get the point.

Thank you.

**Comment by LisaSikkema** [comment]
> If the cluster of cells DC-2 is incorrectly labeled as mono and macro, then the entropy should be low (only one cell type).

No we actually quantify the entropy of the original labels (monocytes and macrophages) in the cluster. As these are contradictory labels, entropy will be higher. If you would calculate entropy among the final annotations for this cluster, it would indeed be low.

The entropy is calculated *per cluster*. If all cells in the cluster have the same label, the entropy will be at its lowest. If all cells in the cluster would each have different labels, it will be at its highest. 
Cells in one cluster can have different labels for two reasons: either multiple cell types are captured in the cluster, and so it is to be expected that the cluster includes multiple labels. In this case it is okay if entropy is high. However, it can also be that a cluster in reality only includes cells of a single cell type, but some of the cells in the cluster were mislabeled as another cell type. In this case, entropy will be high due to partial mislabeling.

Does that clarify things?

**Comment by mugpeng** [comment]
It is clear to me. Thank you very much!
