### ISSUE TITLE
Issues with reproducibility

### ISSUE THREAD

**Issue by Kayla-Morrell** [LungCellAtlas/HLCA_reproducibility#9]
I'm trying to work through the `01a_data_import_and_preprocessing.ipynb` notebook and I'm running into an issue with the raw data. The first issue I run into deals with this code:

```
with open("../../../raw_data_path.txt", "r") as file:
    dir_data = file.readline().strip()
```

The `raw_data_path.txt` file is not part of this repository. I assumed it was just a txt file that contains the path to the raw data on my local computer, but I didn't want to assume incorrectly.

The second issue deals with actually obtaining the raw data. It isn't clear where I can find the data to download it myself, or even which files are needed in order to complete the code under the import data section of the notebook. Looking at the `LCA_file_reading.py` script, it seems raw data files need to be organized in a certain way for the functions to execute. For example, in `read_file_Banovich_Kropski_2020` it looks for `20210414_VUMC.TGen_control_annotation.csv"` in a `01_Metadata` directory, while in `read_file_Barbry_Leroy_2020` it looks for `HCA_Lung_Barbry_Raw_SoupX.h5` and `HCA_Lung_Barbry_Raw.h5` to be in a `04_Counts` directory. 

Would you be able to provide locations for where the raw data can be obtained/downloaded and a structure for how the data should be organized in order to be able to run the notebook to completion?

Best,
Kayla

**Comment by LisaSikkema** [comment]
Hi Kayla,

Yeah that file indeed contained the path to the directory with the raw file on my computer, you can just set `dir_data` to the directory where you have the data and ignore the file.

And yes I haven't made available the raw data I used at the time, as it has undergone so many rounds of cleaning and gene harmonisation etc. since. I still have it on our cluster though

May I ask what you need it for? It would probably be easiest to just use the raw counts of the final object for most tasks, unless you are trying to exactly reproduce some of our intermediate outputs

**Comment by Kayla-Morrell** [comment]
@LisaSikkema - Thank you for your quick response. My boss and I were starting to explore the realm of data harmonization. We found the HLCA paper which led to this repository. It was our plan to follow along a workflow to get a better sense of what steps are needed when starting with raw data all the way through to analysis, though we don't have raw count data of our own. We were hopeful that the notebooks could provide the step by step process that we could attempt to reproduce with the accompanying raw data. We have found a few other avenues to explore but will keep this repo in mind for any further exploration. Thank you!
